# For more info on HTTP files go to https://aka.ms/vs/httpfile
#@baseURL= http://localhost:5108
@baseURL=https://andrewdemonetconf2023api20231231212527.azurewebsites.net/



# @apikey=cec8ad70-fa27-4710-a046-7a8d1e65c0d9
@apikey=d069d4eb-6a1f-49c4-a8d0-3e32079e54b5

@accessToken=e60682fd092141cda91e904843677222

@cartId=2




###
GET {{baseURL}}/api/products
x-api-key: {{apikey}}








###
POST {{baseURL}}/api/member/register
Content-Type: application/json
x-api-key: {{apikey}}

{
  "name": "andrew"
}

###
POST {{baseURL}}/api/member/login
Content-Type: application/json
x-api-key: {{apikey}}

{
  "name": "andrew",
  "password": "123456"
}

###
GET {{baseURL}}/api/member/{{accessToken}}/
x-api-key: {{apikey}}

###
GET {{baseURL}}/api/member/{{accessToken}}/orders
x-api-key: {{apikey}}




###
POST {{baseURL}}/api/carts/create
x-api-key: {{apikey}}


###
POST {{baseURL}}/api/carts/{{cartId}}/items
x-api-key: {{apikey}}
Content-Type: application/json

{
  "productId": 1,
  "qty": 3
}

###
POST {{baseURL}}/api/carts/{{cartId}}/items
x-api-key: {{apikey}}
Content-Type: application/json

{
  "productId": 2,
  "qty": 5
}

###
GET {{baseURL}}/api/carts/{{cartId}}
x-api-key: {{apikey}}


###
POST {{baseURL}}/api/carts/{{cartId}}/estimate
x-api-key: {{apikey}}




###
POST {{baseURL}}/api/checkout/create
x-api-key: {{apikey}}
Content-Type: application/json

{
  "cartId": 1,
  "accessToken": "{{accessToken}}"
}


###
POST {{baseURL}}/api/checkout/complete
x-api-key: {{apikey}}
Content-Type: application/json

{
  "transactionId": 1,
  "accessToken": "{{accessToken}}",
  "paymentId": 9527
}
