# For more info on HTTP files go to https://aka.ms/vs/httpfile
@baseURL= http://localhost:5108
#@baseURL=https://andrewdemonetconf2023api20231231212527.azurewebsites.net/

@apikey=d069d4eb-6a1f-49c4-a8d0-3e32079e54b5
@accessToken=22a18c5cd6db4887af8480f7a0ccc971
@cartId=1
@transactionId=1
@paymentId=6741




@clientid=d1f57db5815f61b857f6
@code=a60c40165a6e2714ed16
@secret=43a8916a12e8fb1a8be39d1763b7d8c27998aa28
@redir=https://chat.openai.com/aip/g-ed6edba8640ce90c45e25af8de0559c3b339d261/oauth/callback


GET https://api.github.com/login/oauth/access_token?client_id={{clientid}}&client_secret={{secret}}&code={{code}}&redirect_uri={{redir}}
User-Agent: VSCode REST Client




## Content-Type: application/x-www-form-urlencoded





###
GET {{baseURL}}/api/products
x-api-key: {{apikey}}








###
POST {{baseURL}}/api/member/register
Content-Type: application/json
x-api-key: {{apikey}}

{
  "name": "andrew"
}

###
POST {{baseURL}}/api/member/login
Content-Type: application/json
x-api-key: {{apikey}}

{
  "name": "andrew",
  "password": "123456"
}

###
GET {{baseURL}}/api/member/{{accessToken}}/
x-api-key: {{apikey}}

###
GET {{baseURL}}/api/member/{{accessToken}}/orders
x-api-key: {{apikey}}




###
POST {{baseURL}}/api/carts/create
x-api-key: {{apikey}}


###
POST {{baseURL}}/api/carts/{{cartId}}/items
x-api-key: {{apikey}}
Content-Type: application/json

{
  "productId": 1,
  "qty": 3
}

###
POST {{baseURL}}/api/carts/{{cartId}}/items
x-api-key: {{apikey}}
Content-Type: application/json

{
  "productId": 2,
  "qty": 5
}

###
GET {{baseURL}}/api/carts/{{cartId}}
x-api-key: {{apikey}}


###
POST {{baseURL}}/api/carts/{{cartId}}/estimate
x-api-key: {{apikey}}




###
POST {{baseURL}}/api/checkout/create
x-api-key: {{apikey}}
Content-Type: application/json

{
  "cartId": {{cartId}},
  "accessToken": "{{accessToken}}"
}


###
POST {{baseURL}}/api/checkout/complete
x-api-key: {{apikey}}
Content-Type: application/json

{
  "transactionId": {{transactionId}},
  "accessToken": "{{accessToken}}",
  "paymentId": {{paymentId}}
}
