# For more info on HTTP files go to https://aka.ms/vs/httpfile
@baseURL= http://localhost:5108
@apikey=cec8ad70-fa27-4710-a046-7a8d1e65c0d9




###
GET {{baseURL}}/api/products
x-api-key: {{apikey}}

###
GET {{baseURL}}/api/member
x-api-key: {{apikey}}

###
GET {{baseURL}}/api/member/orders
x-api-key: {{apikey}}




###
POST {{baseURL}}/api/carts/create
x-api-key: {{apikey}}


###
POST {{baseURL}}/api/carts/1/items
x-api-key: {{apikey}}
Content-Type: application/json

{
  "productId": 1,
  "qty": 3
}

###
POST {{baseURL}}/api/carts/1/items
x-api-key: {{apikey}}
Content-Type: application/json

{
  "productId": 2,
  "qty": 5
}

###
GET {{baseURL}}/api/carts/1
x-api-key: {{apikey}}


###
POST {{baseURL}}/api/carts/1/estimate
x-api-key: {{apikey}}




###
POST {{baseURL}}/api/checkout/create
x-api-key: {{apikey}}
Content-Type: application/json

{
  "cartId": 1
}


###
POST {{baseURL}}/api/checkout/complete
x-api-key: {{apikey}}
Content-Type: application/json

{
  "transactionId": 1,
  "paymentId": 9527
}
